apiVersion: ctl.enisoc.com/v1
kind: BlueGreenDeployment
metadata:
  name: nodeback
  labels:
    app: nodeback
spec:
  replicas: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: nodeback
  template:
    metadata:
      labels:
        app: nodeback
    spec:
      containers:
        - name: nodeback
          image: { { imgWithTag } }
          ports:
            - containerPort: 8083
      imagePullPolicy: Always
  service:
    metadata:
      name: nodeback-svc
      labels:
        app: nodeback
    spec:
      type: NodePort
      selector:
        app: nodeback
      ports:
        - port: 8083
          targetPort: 8083
          protocol: TCP
          nodePort: 31003
