apiVersion: ctl.enisoc.com/v1
kind: BlueGreenDeployment
metadata:
  name: hwga-dwdori
  labels:
    app: hwga-dwdori
spec:
  replicas: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: hwga-dwdori
  template:
    metadata:
      labels:
        app: hwga-dwdori
    spec:
      containers:
        - name: hwga-dwdori
          image: { { imgWithTag } }
          ports:
            - containerPort: 8080
      imagePullPolicy: Always
  service:
    metadata:
      name: hwga-dwdori-svc
      labels:
        app: hwga-dwdori
    spec:
      type: NodePort
      selector:
        app: hwga-dwdori
      ports:
        - port: 8080
          targetPort: 8080
          protocol: TCP
          nodePort: 31005
