apiVersion: ctl.enisoc.com/v1
kind: BlueGreenDeployment
metadata:
  name: pyback
  labels:
    app: pyback
spec:
  replicas: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: pyback
  template:
    metadata:
      labels:
        app: pyback
    spec:
      containers:
        - name: pyback
          image: { { imgWithTag } }
          ports:
            - containerPort: 5000
      imagePullPolicy: Always
  service:
    metadata:
      name: pyback-svc
      labels:
        app: pyback
    spec:
      type: NodePort
      selector:
        app: pyback
      ports:
        - port: 5000
          targetPort: 5000
          protocol: TCP
          nodePort: 31002
