apiVersion: ctl.enisoc.com/v1
kind: BlueGreenDeployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: { { imgWithTag } }
          ports:
            - containerPort: 6379
      imagePullPolicy: Always
  service:
    metadata:
      name: redis-svc
      labels:
        app: redis
    spec:
      type: NodePort
      selector:
        app: redis
      ports:
        - port: 6379
          targetPort: 6379
          protocol: TCP
          nodePort: 31010
